spring.application.name=Morakmorak

# JSP ë·° ì¤ì  - prefixì suffixë¥¼ ì¤ì  (View Resolver)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

## JDBC ë°ì´í°ë² ì´ì¤ ì°ê²°
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=clubsite
spring.datasource.password=123456

# Hikari Datasource ì»¤ë¥ì í ì¤ì  ë° validation query(MySQLììë SELECT 1)
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=8
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

## Mybatis ì¤ì 
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mappers/**/*.xml

## íì¼ ìë¡ë ê´ë ¨ ì¤ì 
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

## ìë¡ë ê²½ë¡ ì¤ì  (ìë²ì ìì ëë í ë¦¬ ê²½ë¡)
upload.path=C:/upload

## ë©ìì§ ë¦¬ìì¤ ì¤ì 
spring.messages.basename=message.message

# ê¸°ë³¸ ë³´ì ì¤ì 
spring.security.user.name=test
spring.security.user.password=test
spring.security.user.roles=MEMBER

# ì¹´ì¹´ì¤ ë¡ê·¸ì¸ API ì¤ì 


# Hibernate Dialect ì¤ì  (Oracleì ìí Dialect)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect


# Hibernate ê´ë ¨ ì¤ì 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#ìí¬ë¦¿í¤ ì¤ì 
jwt.secret=secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
